production:
  adapter: postgresql
  database: daycare_pro
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: daycare_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: daycare_test
  pool: 5
  timeout: 5000
