production:
  adapter: postgresql
  database: superdash_dev
  pool: 5
  timeout: 5000


development:
  adapter: postgresql
  database: superdash_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: superdash_test
  pool: 5
  timeout: 5000
